FROM microsoft/windowsservercore:10.0.14393.2551
RUN ["powershell.exe", "Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"]
CMD ["powershell.exe"]